import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'
import { defineConfig, loadEnv, type Plugin } from 'vite'
import { viteStaticCopy } from 'vite-plugin-static-copy'
import { buildManifest, rootDir } from './manifest.shared.ts'

function writeManifestPlugin(mode: string): Plugin {
  return {
    name: 'vendelo-write-manifest',
    // After publicDir copy so our generated file is the final one.
    closeBundle() {
      const env = loadEnv(mode, path.resolve(rootDir, '../..'), '')
      if (env.VITE_API_URL) {
        process.env.VITE_API_URL = env.VITE_API_URL
      }
      if (env.VITE_SELLER_URL) {
        process.env.VITE_SELLER_URL = env.VITE_SELLER_URL
      } else if (env.VITE_SELLER_APP_URL) {
        process.env.VITE_SELLER_URL = env.VITE_SELLER_APP_URL
      }
      if (env.VITE_WHATSAPP_EXTENSION_KEY) {
        process.env.VITE_WHATSAPP_EXTENSION_KEY = env.VITE_WHATSAPP_EXTENSION_KEY
      }
      const manifest = buildManifest()
      const outPath = path.resolve(rootDir, 'dist/manifest.json')
      fs.mkdirSync(path.dirname(outPath), { recursive: true })
      fs.writeFileSync(outPath, `${JSON.stringify(manifest, null, 2)}\n`)
      console.info(`[vendelo] wrote ${outPath}`)
    },
  }
}

/** Content script build (IIFE). Run first; empties dist/. */
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, path.resolve(rootDir, '../..'), '')
  const apiUrl = env.VITE_API_URL || process.env.VITE_API_URL || 'http://localhost:8000'
  const sellerUrl =
    env.VITE_SELLER_URL ||
    env.VITE_SELLER_APP_URL ||
    process.env.VITE_SELLER_URL ||
    'http://localhost:5174'

  return {
    define: {
      'process.env.NODE_ENV': JSON.stringify('production'),
      'import.meta.env.VITE_API_URL': JSON.stringify(apiUrl),
      'import.meta.env.VITE_SELLER_URL': JSON.stringify(sellerUrl),
    },
    plugins: [
      react(),
      viteStaticCopy({
        targets: [
          { src: 'public/icons', dest: '.' },
          { src: 'public/fonts', dest: '.' },
        ],
      }),
      writeManifestPlugin(mode),
    ],
    // Icons/fonts via viteStaticCopy; manifest generated by plugin.
    publicDir: false,
    resolve: {
      alias: {
        '@': path.resolve(rootDir, './src'),
      },
    },
    build: {
      outDir: 'dist',
      emptyOutDir: true,
      cssCodeSplit: false,
      modulePreload: false,
      target: 'es2022',
      minify: true,
      rollupOptions: {
        input: path.resolve(rootDir, 'src/content.ts'),
        output: {
          format: 'iife',
          name: 'VendeloWhatsAppWeb',
          entryFileNames: 'content.js',
          inlineDynamicImports: true,
          assetFileNames: 'assets/[name][extname]',
        },
      },
    },
  }
})
